apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    namespace: default
    server: 'aksdemo-dns-j4gh412w.hcp.westeurope.azmk8s.io'
  project: default
  source:
    repoURL: 'https://github.com/DevOpsCrafter/gitops-argocd'
    path: ./manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
