apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    namespace: default
    server: 'akstest-dns-fggp9781.hcp.centralindia.azmk8s.io'
  project: default
  source:
    repoURL: 'https://github.com/DevOpsCrafter/gitops-argocd'
    path: ./manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
