apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: testacrpd.azurecr.io/myimage:e7a4202
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-registry-credentials
                  key: username
            - name: REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-registry-credentials
                  key: password
