name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push the Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build, tag, and push image to Azure Container Registry (ACR)
        env:
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        run: |
          git_hash=$(git rev-parse --short "${{ github.sha }}")
          image_tag="$git_hash"
          docker build -t $REGISTRY_NAME.azurecr.io/myimage:${{ github.run_number }} .
          echo "Pushing image to ACR..."
          docker push $REGISTRY_NAME.azurecr.io/myimage:${{ github.run_number }}

#       - name: Update version
#         run: | 
#           git_hash=$(git rev-parse --short "${{ github.sha }}")
#           sed -Ei "s/(version:).*/\1 refs\/heads\/main-$git_hash/" ./manifests/deployment.yml

#       - name: Commit and push changes
#         uses: devops-infra/action-commit-push@v0.3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           commit_message: Version updated

  Update-K8s-Manifests:
    name: Update K8s Deployment Manifest with Image Version
    #needs: BuildPush
    environment: ${{ inputs.Environment }}
    runs-on: ubuntu-latest
    steps:

    # Checks out the baseline repository
    - uses: actions/checkout@v2

    - name: Update image name in manifest file
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $line = Get-Content manifests/deployment.yml | Select-String image: | Select-Object -ExpandProperty Line
          $content = Get-Content manifests/deployment.yml
          $content | ForEach-Object {$_ -replace $line,"        image: ${{ inputs.ACRNAME }}.azurecr.io/${{ inputs.APPNAME }}:${{ github.run_number }}"} | Set-Content manifests/deployment.yml
        azPSVersion: "latest"
    
    - name: Commit changes in manifest to repo
      run: | 
        git config user.name "GitHub Actions Bot"
        git config user.email ""
        git add manifests/deployment.yaml
        git commit -m "Update image version in K8s Deployment manifests file"
        git push origin
        git commit -m "Update image version in K8s Deployment manifests file"
        git push origin
  
